call pathogen#infect()
call pathogen#helptags()

syntax on
filetype plugin indent on

" forget old vim
set nocompatible
set modelines=0

" gvim/macvim specific
set winaltkeys=no
set macmeta
set transparency=5
set nobeval
macmenu File.Print key=<nop>

colorscheme peaksea " easier on the eyes than vividchalk

" tab and spaces
set tabstop=8
set shiftwidth=2
set softtabstop=2
set expandtab
set listchars=tab:▸\ ,eol:¬

" backup
set undodir=~/.vim/tmp/undo//     " undo files
set backupdir=~/.vim/tmp/backup// " backups
set directory=~/.vim/tmp/swap//   " swap files
set nobackup
set nowritebackup
set noswapfile

" TODO: comments
set encoding=utf-8
set scrolloff=10
set autoindent
set showmode
set showcmd
set hidden
set wildmenu
set wildmode=list:longest
set visualbell
set nocursorline
set ttyfast
set ruler
set backspace=indent,eol,start
set laststatus=2
set undofile
set norelativenumber
set number
set foldmethod=manual

" include underscore in word movements
set iskeyword+=_

" wrapping
set nowrap
set linebreak
"set textwidth=79
"set nolinebreak
set formatoptions=qrn1
"set colorcolumn=85

" navigation
"nnoremap ' `
"nnoremap ` '
nnoremap <C-a> ^
nnoremap <C-e> $

" search/move
nnoremap / /\v
vnoremap / /\v
set ignorecase
set smartcase
set gdefault "/g is default
set incsearch
set showmatch
set hlsearch
"nnoremap <tab> %
"vnoremap <tab> %
nnoremap <leader><space> :noh<cr>

" educational>
inoremap <Left>  <Left>
inoremap <Right> <Right>
inoremap <Up>    <Up>
inoremap <Down>  <Down>
nnoremap <Left>  <Left>
nnoremap <Right> <Right>
nnoremap <Up>    <Up>
nnoremap <Down>  <Down>
"nnoremap <up> <nop>
"nnoremap <down> <nop>
"nnoremap <left> <nop>
"nnoremap <right> <nop>
"inoremap <up> <nop>
"inoremap <down> <nop>
"inoremap <left> <nop>
"inoremap <right> <nop>
nnoremap j gj
nnoremap k gk

" leader
let mapleader = ","

" substitute under visual
function! GetVisual() range
    let reg_save = getreg('"')
    let regtype_save = getregtype('"')
    let cb_save = &clipboard
    set clipboard&
    normal! ""gvy
    let selection = getreg('"')
    call setreg('"', reg_save, regtype_save)
    let &clipboard = cb_save
    return selection
endfunction
vmap <leader>s :<c-U>%s/<c-r>=GetVisual()<cr>/

" misc leader mappings
nnoremap <leader>ev <C-w>s<C-w>j<C-w>L:e $MYGVIMRC<cr>

"nnoremap <leader>v V`]
"nnoremap <Leader>s :%s/\<<C-r><C-w>\>/

" f keys
nmap <F3> :set list!<cr>
nnoremap <F4> :set nolist wrap!<cr>

" fold html tag
nnoremap <leader>ft Vatzf

" window, tab and split screen navigation
nnoremap <S-D-v> <C-w>v<C-w>l
nnoremap <S-D-h> <C-w>s<C-w>l
noremap <D-j> <C-w>w
noremap <D-k> <C-w>W
nnoremap <D-1> 1gt
inoremap <D-1> 1gt
nnoremap <D-2> 2gt
inoremap <D-2> 2gt
nnoremap <D-3> 3gt
inoremap <D-3> 3gt
nnoremap <D-4> 4gt
inoremap <D-4> 4gt
nnoremap <D-5> 5gt
nnoremap <D-6> 6gt
nnoremap <D-7> 7gt
nnoremap <D-8> 8gt
nnoremap <D-9> 9gt
nnoremap <D-0> 10g

" iMacfiy
nnoremap <D-z> u
nnoremap <D-S-z> <C-r>

" ack
nnoremap <leader>a :Ack -i 

" fugitive (git)
nnoremap <leader>gs :Gstatus<cr>
nnoremap <leader>gc :Gcommit<cr>
nnoremap <leader>gw :Gwrite<cr>
nnoremap <leader>gr :Gread<cr>
nnoremap <leader>grm :Gremove<cr>
nnoremap <leader>gmv :Gmove<cr>

" nerdtree
map <F1> :NERDTreeToggle \| :silent NERDTreeMirror<CR>
inoremap <F1> <esc>:NERDTreeToggle<cr>
let NERDTreeIgnore=['.vim$', '\~$', '.*\.pyc$', 'pip-log\.txt$', 'whoosh_index', 'xapian_index', '.*.pid', 'monitor.py', '.*-fixtures-.*.json', '.*\.o$', 'db.db']
au Filetype nerdtree setlocal nolist

" tasklist
nnoremap <leader>k <Plug>TaskList

" command-t
nnoremap <leader>fl :CommandTFlush<cr>

" go to work directory
"command Store :exec "chdir /media/sandbox/workspace/meteor-prototype-catalog-apis"
"command Catalog :exec "chdir /media/sandbox/workspace/emobile-catalog"

" Toggle fold state between closed and opened.
"
" If there is no fold at current line, just moves forward.
" If it is present, reverse it's state.

fu! ToggleFold()
  if foldlevel('.') == 0
    normal! l
  else
    if foldclosed('.') < 0
      . foldclose
    else
      . foldopen
    endif
  endif
  echo
endf

" Map this function to Space key.
noremap <space> :call ToggleFold()<CR> 

" Keys for ctags
map <f9> :!ctags -R --exclude=.git --exclude=.svn --exclude=log * /Users/neektza/.rbenv/versions/1.8.7-p352/lib/ruby/gems/1.8/gems/* /Users/neektza/.rbenv/versions/1.9.2-p290/lib/ruby/gems/1.9.1/gems/*
nnoremap <M-]> <C-]>
nnoremap <M-[> <C-t>
nnoremap <M-n> :tn<cr>
nnoremap <M-p> :tp<cr>

" Trailing whitespace removal
map <f8> :%s/\s\+$//<cr>

map <leader>r :MRU<cr>

runtime vim/bundle/vim-matchit/plugin/matchit.vim
 
