call pathogen#infect()
call pathogen#helptags()

syntax on
filetype plugin indent on

" forget old vim
set nocompatible
set modelines=0

" leader
let mapleader = ","

" clipboard
set clipboard=unnamed

" easier on the eyes than vividchalk
set t_Co=256
set background=dark
colorscheme peaksea

" tab and spaces
set tabstop=8
set shiftwidth=2
set softtabstop=2
set expandtab
"set listchars=tab:▸\ ,eol:¬
nmap <F1> :set list!<cr>

" backup
set undodir=~/.vim/tmp/undo//     " undo files
set backupdir=~/.vim/tmp/backup// " backups
set directory=~/.vim/tmp/swap//   " swap files
set nobackup
set nowritebackup
set noswapfile

" settings 
set encoding=utf-8
set scrolloff=10
set autoindent
set showmode
set showcmd
set hidden
set wildmenu
set wildmode=list:longest
set visualbell
set nocursorline
set ttyfast
set ruler
set backspace=indent,eol,start
set laststatus=2
set number 
set undofile
set norelativenumber
set number
set foldmethod=manual

" include underscore in word movements
set iskeyword+=_

" wrapping
set nowrap
set linebreak
set textwidth=79
set formatoptions=qrn1
"set colorcolumn=85

" navigation
"nnoremap ' `
"nnoremap ` '
nnoremap <C-a> ^
nnoremap <C-e> $

" window, tab and split screen navigation
map <leader>t :tabnew<cr>
nnoremap <leader>v :vsplit<cr>
nnoremap <leader>h :split<cr>
nnoremap <C-h> <C-w>h
nnoremap <C-j> <C-w>j
nnoremap <C-k> <C-w>k
nnoremap <C-l> <C-w>l


" search/move
nnoremap / /\v
vnoremap / /\v
set ignorecase
set smartcase
set gdefault "/g is default
set incsearch
set showmatch
set hlsearch
"nnoremap <tab> %
"vnoremap <tab> %
nnoremap <leader><space> :noh<cr>

nnoremap j gj
nnoremap k gk

" misc leader mappings
nnoremap <leader>ev <C-w>s<C-w>j<C-w>L:e $MYGVIMRC<cr>
nnoremap <leader>wr :set wrap!<cr>

" function keys
nmap <F3> :set list!<cr>
nnoremap <F4> :set nolist wrap!<cr>

" fold html tag
nnoremap <leader>ft Vatzf

" ack
nnoremap <leader>a :Ack -i

" fugitive (git)
nnoremap <leader>gs :Gstatus<cr>
nnoremap <leader>gc :Gcommit<cr>
nnoremap <leader>gw :Gwrite<cr>
nnoremap <leader>gr :Gread<cr>
nnoremap <leader>grm :Gremove<cr>
nnoremap <leader>gmv :Gmove<cr>

" nerdtree
map <F1> :NERDTreeToggle \| :silent NERDTreeMirror<cr>
inoremap <F1> <esc>:NERDTreeToggle<cr>
let NERDTreeIgnore=['.vim$', '\~$', '.*\.pyc$', 'pip-log\.txt$', 'whoosh_index', 'xapian_index', '.*.pid', 'monitor.py', '.*-fixtures-.*.json', '.*\.o$', 'db.db']
au Filetype nerdtree setlocal nolist

" ctrlp
let g:ctrlp_map = ''
let g:ctrlp_cmd = 'CtrlP'
nnoremap <leader>f :CtrlP<cr>
nnoremap <leader>m :CtrlPMRUFiles<cr>
nnoremap <f5> :CtrlPClearCache<cr>
set wildignore+=*/tmp/*,*.so,*.swp,*.zip,*.log

" insert mode toggling
" nnoremap <C-space> a
" imap <C-space> <Esc>

" disable ex mode
nnoremap <silent> Q ZZ

map <A-f> :CtrlP<cr>
