call pathogen#infect()
call pathogen#helptags()

syntax on
filetype plugin indent on

" forget old vim
set nocompatible
set modelines=0

" easier on the eyes than vividchalk
colorscheme peaksea

" tab and spaces
set tabstop=8
set shiftwidth=2
set softtabstop=2
set expandtab
"set listchars=tab:▸\ ,eol:¬
nmap <F1> :set list!<cr>


" backup
set undodir=~/.vim/tmp/undo//     " undo files
set backupdir=~/.vim/tmp/backup// " backups
set directory=~/.vim/tmp/swap//   " swap files
set nobackup
set nowritebackup
set noswapfile

" TODO: comments
set encoding=utf-8
set scrolloff=10
set autoindent
set showmode
set showcmd
set hidden
set wildmenu
set wildmode=list:longest
set visualbell
set cursorline
set ttyfast
set ruler
set backspace=indent,eol,start
set laststatus=2
set number 
set undofile
set norelativenumber
set number
set foldmethod=manual

" include underscore in word movements
set iskeyword+=_

" wrapping
set nowrap
set linebreak
set textwidth=79
set formatoptions=qrn1
"set colorcolumn=85

" navigation
"nnoremap ' `
"nnoremap ` '
nnoremap <C-a> ^
nnoremap <C-e> $

" search/move
nnoremap / /\v
vnoremap / /\v
set ignorecase
set smartcase
set gdefault "/g is default
set incsearch
set showmatch
set hlsearch
"nnoremap <tab> %
"vnoremap <tab> %
nnoremap <leader><space> :noh<cr>

inoremap <Left>  <Left>
inoremap <Right> <Right>
inoremap <Up>    <Up>
inoremap <Down>  <Down>
nnoremap <Left>  <Left>
nnoremap <Right> <Right>
nnoremap <Up>    <Up>
nnoremap <Down>  <Down>
nnoremap j gj
nnoremap k gk

" leader
let mapleader = ","

" misc leader mappings
nnoremap <leader>ev <C-w>s<C-w>j<C-w>L:e $MYGVIMRC<cr>
nnoremap <leader>wr :set wrap!<cr>

" f keys
nmap <F3> :set list!<cr>
nnoremap <F4> :set nolist wrap!<cr>

" fold html tag
nnoremap <leader>ft Vatzf

" window, tab and split screen navigation
nnoremap <leader>v :vsplit<cr>
noremap <D-j> <C-w>w
noremap <D-k> <C-w>W
nnoremap <D-1> 1gt
inoremap <D-1> 1gt
nnoremap <D-2> 2gt
inoremap <D-2> 2gt
nnoremap <D-3> 3gt
inoremap <D-3> 3gt
nnoremap <D-4> 4gt
inoremap <D-4> 4gt
nnoremap <D-5> 5gt
nnoremap <D-6> 6gt
nnoremap <D-7> 7gt
nnoremap <D-8> 8gt
nnoremap <D-9> 9gt
nnoremap <D-0> 10g

" iMacfiy
nnoremap <D-z> u
nnoremap <D-S-z> <C-r>

" ack
nnoremap <leader>a :Ack -i

" fugitive (git)
nnoremap <leader>gs :Gstatus<cr>
nnoremap <leader>gc :Gcommit<cr>
nnoremap <leader>gw :Gwrite<cr>
nnoremap <leader>gr :Gread<cr>
nnoremap <leader>grm :Gremove<cr>
nnoremap <leader>gmv :Gmove<cr>

" nerdtree
map <F1> :NERDTreeToggle \| :silent NERDTreeMirror<CR>
inoremap <F1> <esc>:NERDTreeToggle<cr>
let NERDTreeIgnore=['.vim$', '\~$', '.*\.pyc$', 'pip-log\.txt$', 'whoosh_index', 'xapian_index', '.*.pid', 'monitor.py', '.*-fixtures-.*.json', '.*\.o$', 'db.db']
au Filetype nerdtree setlocal nolist

" ctrlp
let g:ctrlp_map = '<leader>t'
let g:ctrlp_cmd = 'CtrlP'
set wildignore+=*/tmp/*,*.so,*.swp,*.zip

" insert mode toggling
nnoremap <C-space> a
imap <C-space> <Esc>
