#!/bin/bash
# Runs Clojure using the classpath specified in the `.clojure` file of the
# current directory.
#
# Mark Reid <http://mark.reid.name>
# CREATED: 2009-03-29
JAVA=/usr/bin/java
CLOJURE=/usr/local/Cellar/clojure/1.4.0/clojure-1.4.0.jar
CONTRIB=/usr/local/Cellar/clojure-contrib/1.2.0/clojure-contrib.jar
JLINE=$HOME/bin/clojure-framework/jline-1.0.jar
CP=$PWD:$CLOJURE:$JLINE:$CONTRIB

# Add extra jars as specified by `.clojure` file
if [ -f .clojure ]
then
	CP=$CP:`cat .clojure`
fi

if [ -z "$1" ]; then 
	$JAVA -server -cp $CP \
	    jline.ConsoleRunner clojure.lang.Repl    
else
	scriptname=$1
	$JAVA -server -cp $CP clojure.lang.Script $scriptname -- $*
fi
